### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by raphaeltimbo** [open-pulse/OpenPulse#184]
I don't know if it is possible to do this with cx_freeze, but it would be nice to have the release of the .msi files automated with github actions.
The idea would be to trigger the release process when a tagged commit is pushed to the master branch.
The github action would run, create the .msi file and add it to the 'Releases' page of the repository.
I saw this blog post explaining how to do it with pyinstaller:
https://anshumanfauzdar.medium.com/using-github-actions-to-bundle-python-application-into-a-single-package-and-automatic-release-834bd42e0670

**Comment by andrefpf** [comment]
This enhancement was implemented for version 2.0. Closing issue.
