### ISSUE TITLE
Improve geometry editor

### ISSUE THREAD

**Issue by andrefpf** [open-pulse/OpenPulse#194]
OPPS has some problems that need to be addressed until the final 2.0.0 version.
This is a huge issue that can be divided when the major problems are solved.

# The problems
- ~~The points selection is not working as expected. Some points are not correctly clickable, specially in between continuous pipes.~~
- Curvatures should not be updated several times.
- It should be possible to add pipes and beams in the middle of curvatures.
- It should be possible to add new points and continue the pipeline from them (It also means that the points should not be inferred from the pipeline structures, and we should keep track of points even if it is not connected to a structure).

# Usability/Functional Improvements
- Add wall thickness property to pipe objects
- Implement new beams:
    - Circular
    - Rectangular
    - I
    - T
    - C
- Implement new components:
    - Excentric reduccer
    - Valve
    - Tee Joint
    - Y Joint

**Comment by JacsonGilVargas** [comment]
Excellent job, mission accomplished.
