### ISSUE TITLE
Cannot Edit Iges import

### ISSUE THREAD

**Issue by prm98** [open-pulse/OpenPulse#203]
Import isogen file fails to import one of the bends.  Then, Add/Edit in 'Geometry workspace' does not permit adding a segment to replace the missing bend.
OS: win10 64bit.

![Screenshot 2024-04-07 212218](https://github.com/open-pulse/OpenPulse/assets/63119818/c13fe5b6-044e-4f84-a098-67e3f7aafdd5)

**Comment by andrefpf** [comment]
Hi, thanks for your contribuition!

This feature (to connect two points with a bend) is currently under development.
However, can you send us the example file that the software is failing to import?

**Comment by prm98** [comment]
Hi,
Thank you for replying.
I created this file using Ansys Spaceclaim 2019R3.

two alternate questions, if I may ask:
1) Do you have a tutorial for creating branched geometries, that is,
creating a branched geometry within openPulse without an import?  I did not
find one on Git or on your youtube channel.
2) Is there a way to build a model by simply writing the 'entiy.dat' file?
That may be a way to import other software models (e.g. CaesarII or
Autopipe).

Thanks,
Patrick

**Comment by prm98** [comment]
Here is another iges file that does not import.

Multiple versions of these two messages appear then the exe crashes.
[image: image.png]  [image: image.png]

**Comment by andrefpf** [comment]
I did not received the files.
I guess it is because you sent the file through email instead of the github issues.

**Comment by prm98** [comment]
Sorry about that.  GitHub didn't allow uploading iges files...

**Comment by andrefpf** [comment]
Maybe you can try inside a zip file.

**Comment by prm98** [comment]
trying zip file

**Comment by andrefpf** [comment]
You can send it to my email at fpf.andre@gmail.com
