### ISSUE TITLE
Deselecte point/structure when using CTRL

### ISSUE THREAD

**Issue by raphaeltimbo** [open-pulse/OpenPulse#242]
In the geometry editor, when selecting points/structures if the user wants to deselect a point they have to use ALT. 
One sugestion is to deselect after clicking again with CTRL.
This is the behavior that we have on windows for selecting/deselecting files and it could be more intuitive for the user.

**Comment by andrefpf** [comment]
Fixed. And if the user still wants the previous behaviour it can be achieved by using "shift" instead.
