### ISSUE TITLE
Units for mode shape visualization

### ISSUE THREAD

**Issue by atbrandao** [open-pulse/OpenPulse#28]
The software currently indicates `Unit (m)` when displaying the mode shape plots.

I believe that, for the sake of conceptual consistency, something like "Dimensionless displacement" would be more adequate, since it is only the representation of the eigenvectors, which is a dimensionless entity.

**Comment by olavosilva** [comment]
@atbrandao Perfect. We will corrrect this issue.

**Comment by olavosilva** [comment]
Modification done by @JacsonGilVargas
