### ISSUE TITLE
Error when Running Modal Acoustic Analaysis 

### ISSUE THREAD

**Issue by atbrandao** [open-pulse/OpenPulse#30]
After setting the fluid and 2 specific impedance for the geometry, I tried to run the Acoustic Modal Analysis for the system and the software shut off and returned the following error:

>[Set Specific Impedance] - defined in the point(s) [1186]
[Set Specific Impedance] - defined in the point(s) [1086]
Traceback (most recent call last):
  File "C:\Users\hr7o\Documents\Portable Git\OpenPulse_f\pulse\uix\treeUi.py", l
ine 194, in on_click_item
    self.mainWindow.getInputWidget().analysisTypeInput()
  File "C:\Users\hr7o\Documents\Portable Git\OpenPulse_f\pulse\uix\inputUi.py",
line 252, in analysisTypeInput
    self.runAnalysis()
  File "C:\Users\hr7o\Documents\Portable Git\OpenPulse_f\pulse\uix\inputUi.py",
line 308, in runAnalysis
    solve = self.project.get_acoustic_solve()
  File "C:\Users\hr7o\Documents\Portable Git\OpenPulse_f\pulse\project.py", line
 596, in get_acoustic_solve
    return SolutionAcoustic(self.mesh, self.frequencies)
  File "C:\Users\hr7o\Documents\Portable Git\OpenPulse_f\pulse\processing\soluti
on_acoustic.py", line 11, in __init__
    if frequencies[0]==0:
TypeError: 'NoneType' object is not subscriptable

**Comment by olavosilva** [comment]
@atbrandao The FETM is not able to perform acoustic modal analysis in this stage of implementation. There is a mathematical issue that @dmtuozzo is trying to solve. However, we have a "plan B" to implement acoustic modal analysis, and we are working on that.

**Comment by olavosilva** [comment]
Error eliminated by @JacsonGilVargas  (now, Acoustic Modal Analysis is not enabled in the present version of OpenPulse). We are working on the best way to perform this analysis. We promote "bug" to "enhancement".

**Comment by olavosilva** [comment]
Done!
